version: "3.7"
services:
  web:
    build: ./web
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://postgres:postgres@db:5432/exchange-buy-games"
      NEXT_DEV: 1
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/opt/app/src
    command: npm run dev
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "exchange-buy-games"
      POSTGRES_HOST_AUTH_METHOD: "trust"

